spring:
  devtools:
    add-properties: false
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /hconsole
      console.settings.trace: true
      spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:namegendb
    username: gendb
    password: g3ndb
    driverClassName: org.h2.Driver
    initialization-mode: always
    data: "classpath:data.sql"
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
management:
  metrics:
    export:
      defaults:
        enabled: false
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO